### PR TITLE
Fix cchar definition on aarch64 macos (e.g. M1)

### LINKED ISSUE #18: aarch64-apple-darwin target has wrong c_char
It should be `i8`, not `u8`, as far as I can tell.

### PR DESCRIPTION
**Pull request by thomcc**
Fixes #18. Note that I'd also like to do something like this in test/test.rs, but it would only work on targets with libstd, which isn't something I know how to filter.

```rust
#[test]
fn check_vs_std() {
    let _: cty::c_char = 0 as std::os::raw::c_char;
    let _: cty::c_schar = 0 as std::os::raw::c_schar;
    let _: cty::c_uchar = 0 as std::os::raw::c_uchar;
    let _: cty::c_short = 0 as std::os::raw::c_short;
    let _: cty::c_ushort = 0 as std::os::raw::c_ushort;
    let _: cty::c_int = 0 as std::os::raw::c_int;
    let _: cty::c_uint = 0 as std::os::raw::c_uint;
    let _: cty::c_long = 0 as std::os::raw::c_long;
    let _: cty::c_ulong = 0 as std::os::raw::c_ulong;
    let _: cty::c_longlong = 0 as std::os::raw::c_longlong;
    let _: cty::c_ulonglong = 0 as std::os::raw::c_ulonglong;
}
```

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -33,6 +33,16 @@ mod ad {
     pub type c_uint = u32;
 }
 
+// TODO: Once https://github.com/rust-lang/rfcs/pull/2992 lands,
+// this should be extended to cover `aarch64-apple-ios-macabi`.
+#[cfg(all(target_arch = "aarch64", target_os = "macos"))]
+mod ad {
```
Comment (thomcc) [inline src/lib.rs:39]: This being `mod ad` isn't really true, but I'm not sure where to put it.

**Comment by thomcc** [comment]
Ping: There are a lot of crates in the ecosystem that use `cty`, so it would be very nice to fix this.

**Comment by sanbox-irl** [comment]
ping

**Comment by thomcc** [comment]
@japaric Any chance you can look at (or merge) this?

It's very easy to hit this issue, since `c_char` is (obviously) very widely used.

**Comment by japaric** [comment]
PR included in release v0.2.2
